In [1]:
import pandas as pd
aa = pd.read_csv("C:/Users/lclai/Desktop/aa.csv")
aa

C:\Users\lclai\AppData\Local\Temp\ipykernel_17172\568574640.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

   aminoacid     FORMULA  TYPE     IDS
0        ALA     C3H7NO2     0    5950
1        GLY     C2H5NO2     0     750
2        VAL    C5H11NO2     0    6287
3        CYS    C3H7NO2S     0    5862
4        PRO     C5H9NO2     0  145742
5        LEU    C6H13NO2     0    6106
6        ILE    C6H13NO2     0    6306
7        MET   C5H11NO2S     0    6137
8        TRP  C11H12N2O2     0    6305
9        PHE    C9H11NO2     0    6140
10       LYS   C6H14N2O2     1    5962
11       ARG   C6H14N4O2     1    6322
12       HIS    C6H9N3O2     1    6274
13       ASP     C4H7NO4     2    5960
14       GLU     C5H9NO4     2   33032
15       SER     C3H7N03     3    5951
16       THR     C4H9NO3     3    6288
17       TYR    C9H11NO3     3    6057
18       ASN    C4H8N2O3     3    6267
19       GLN   C5H10N2O3     3     728

TYPE has de following correspondance:

0 --> non polar

1 --> positively charged

2 --> negatively charged

3 --> polar

In [4]:
ids = aa['IDS']
ids.to_csv('pubmedids_aa.csv', index=False, header=False)
ids

0       5950
1        750
2       6287
3       5862
4     145742
5       6106
6       6306
7       6137
8       6305
9       6140
10      5962
11      6322
12      6274
13      5960
14     33032
15      5951
16      6288
17      6057
18      6267
19       728
Name: IDS, dtype: int64